### ISSUE TITLE
User Story 1

### ISSUE THREAD

**Issue by Kachev** [Kachev/Capsone-Project-work-report-#3]
## Value Proposition

- As a User
- I want a list of forms
- in order to fill in

## Description

![Image](https://user-images.githubusercontent.com/93873677/227503415-093b5141-544f-4218-b233-d4f35f478ca9.png)

- Scribble, design, text

## Acceptance criteria

- [ ] Each Information as a different input field
- [ ] Each card has a " + " button, witch sets a new field
- [ ] The list is scrollable
- [ ] The title is displayed above the rides list and is not fixed

## Tasks

- [ ] Create branch
- [ ] Write tests
- [ ] Generate dummy-data
- [ ] Global styles
- [ ] Create db.js with specified information

**Comment by liebeckm** [comment]
great project! ☺️
one small hint from my side:
- specify which cards do get the "+" button; as far as I understand, not all cards do get this (e.g. Kunde).

**Comment by LuYujin9** [comment]
A toll project. There are my suggestions:

- the title should be only "Creating a form", without "title" and "user story 1". Thomas gave me the same suggestion before.
- maybe it is too much for one user story. How about deal with one card  first? e.g. the "Arbeitszeiten"

**Comment by abieber1408** [comment]
Your Project is very useful. I like it very much!!😊

° Perhaps these should by splitter in two Stories to simplify your work and stay focus.
